//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS_PEACE_Client {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    public sealed partial class GlobalSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GlobalSettings defaultInstance = ((GlobalSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GlobalSettings())));
        
        public static GlobalSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240, 201, 135")]
        public global::System.Drawing.Color Attack1color {
            get {
                return ((global::System.Drawing.Color)(this["Attack1color"]));
            }
            set {
                this["Attack1color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("97, 137, 133")]
        public global::System.Drawing.Color Attack2color {
            get {
                return ((global::System.Drawing.Color)(this["Attack2color"]));
            }
            set {
                this["Attack2color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("149, 125, 149")]
        public global::System.Drawing.Color Attack3color {
            get {
                return ((global::System.Drawing.Color)(this["Attack3color"]));
            }
            set {
                this["Attack3color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("239, 111, 108")]
        public global::System.Drawing.Color Attack4color {
            get {
                return ((global::System.Drawing.Color)(this["Attack4color"]));
            }
            set {
                this["Attack4color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90, 105, 236")]
        public global::System.Drawing.Color Ownlandcolor {
            get {
                return ((global::System.Drawing.Color)(this["Ownlandcolor"]));
            }
            set {
                this["Ownlandcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("215, 94, 67")]
        public global::System.Drawing.Color Elselandcolor {
            get {
                return ((global::System.Drawing.Color)(this["Elselandcolor"]));
            }
            set {
                this["Elselandcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("213, 213, 213")]
        public global::System.Drawing.Color Targeted {
            get {
                return ((global::System.Drawing.Color)(this["Targeted"]));
            }
            set {
                this["Targeted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Attack 1")]
        public string Attack1name {
            get {
                return ((string)(this["Attack1name"]));
            }
            set {
                this["Attack1name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Attack 2")]
        public string Attack2name {
            get {
                return ((string)(this["Attack2name"]));
            }
            set {
                this["Attack2name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Attack 3")]
        public string Attack3name {
            get {
                return ((string)(this["Attack3name"]));
            }
            set {
                this["Attack3name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Attack 4")]
        public string Attack4name {
            get {
                return ((string)(this["Attack4name"]));
            }
            set {
                this["Attack4name"] = value;
            }
        }
    }
}
